# MITIGATING TRAFFIC CONGESTION : END-TO-END MACHINE LEARNING PROJECT

This project looks at prediction of traffic in a particular public road in order to determine time periods of lesser traffic congestions.

## DATA LOADING

In [1]:
!pip install kaggle

Requirement already satisfied: kaggle in C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages (2.2.4)
Requirement already satisfied: bleach in C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages (from kaggle) (6.3.0)
Requirement already satisfied: jupytext in C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages (from kaggle) (1.19.5)
Requirement already satisfied: kagglesdk<1.0,>=0.1.35 in C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages (from kaggle) (0.1.37)
Requirement already satisfied: packaging in C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages (from kaggle) (26.2)
Requirement already satisfied: protobuf in C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages (from kaggle) (7.35.1)
Requirement already satisfied: python-dateutil in C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-dotenv in C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages (from kaggle) (1.2.2)
Requirement already satisfied: python-slugify in C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages (from kaggle) (2.33.1)
Requirement already satisfied: tqdm in C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages (from kaggle) (4.67.3)
Requirement already satisfied: urllib3>=1.15.1 in C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages (from kaggle) (2.7.0)
Requirement already satisfied: webencodings in C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: markdown-it-py>=1.0 in C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jupytext->kaggle) (4.2.0)
Requirement already satisfied: mdit-py-plugins in C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jupytext->kaggle) (0.6.1)
Requirement already satisfied: nbformat in C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jupytext->kaggle) (5.10.4)
Requirement already satisfied: pyyaml in C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jupytext->kaggle) (6.0.3)
Requirement already satisfied: mdurl~=0.1 in C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages (from markdown-it-py>=1.0->jupytext->kaggle) (0.1.2)
Requirement already satisfied: fastjsonschema>=2.15 in C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages (from nbformat->jupytext->kaggle) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages (from nbformat->jupytext->kaggle) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages (from nbformat->jupytext->kaggle) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages (from nbformat->jupytext->kaggle) (5.15.0)
Requirement already satisfied: attrs>=22.2.0 in C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.30.0)
Requirement already satisfied: platformdirs>=2.5 in C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat->jupytext->kaggle) (4.9.6)
Requirement already satisfied: six>=1.5 in C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages (from python-dateutil->kaggle) (1.17.0)
Requirement already satisfied: text-unidecode>=1.3 in C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests->kaggle) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests->kaggle) (3.13)
Requirement already satisfied: certifi>=2023.5.7 in C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests->kaggle) (2026.4.22)
Requirement already satisfied: colorama in C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages (from tqdm->kaggle) (0.4.6)

In [2]:
import kaggle 

print("Kaggle package installed successfully")

Kaggle package installed successfully

In [3]:
import os

kaggle_dir = os.path.expanduser("~/.kaggle")
os.makedirs(kaggle_dir, exist_ok=True)

print(kaggle_dir)

C:\Users\user/.kaggle

In [ ]:
token = input("Paste your Kaggle API token: ")

token_path = os.path.expanduser("~/.kaggle/access_token")

with open(token_path, "w") as f:
    f.write(token.strip())

print("Kaggle token saved successfully.")

NOTE : Don't make above token public.

In [4]:
# Obtain dataset identifier 
# (Optional)

!kaggle datasets list -s "travel time prediction"

ref                                                             title                                                     size  lastUpdated                 downloadCount  voteCount  usabilityRating
--------------------------------------------------------------  --------------------------------------------------  ----------  --------------------------  -------------  ---------  ---------------
ekaettesamuel/travel-time-prediction-in-lagos-nigeria           Lagos Travel Time Prediction                             87242  2025-09-14 03:58:49.580000             31          0  0.23529412
pkdarabi/classification-of-travel-purpose                       Travel Ticket Cancellations for Risk Management        7656837  2023-08-15 17:23:58.320000           1256        103  0.9411765
rauffauzanrambe/smart-city-traffic-flow-prediction-dataset      Smart City Traffic Flow Prediction Dataset             3591830  2026-05-31 10:13:05.283000           1749         45  1
pratyushpuri/multilingual-mobile-app-reviews-dataset-2025       Multilingual Mobile App Review Dataset Sept 2025        136331  2025-07-31 03:09:08.217000           7604        306  1
mahatiratusher/flight-price-dataset-of-bangladesh               Flight Price Dataset of Bangladesh                     3506315  2025-03-04 04:08:49.600000           4083         38  0.9411765
whenamancodes/student-performance                               Student Performance                                     106753  2022-10-07 05:14:47.567000          43205        506  1
raviiloveyou/predict-taxi-fare-with-a-bigquery-ml-forecasting   Taxi trip fare prediction                              3024126  2023-06-13 10:09:05.027000           5535         54  1
whenamancodes/alcohol-effects-on-study                          Alcohol Effects On Study                                 18566  2022-09-15 03:21:04.560000          19024        230  1
crailtap/taxi-trajectory                                        Taxi Trajectory Data                                 540159049  2018-04-12 11:41:23.040000          12344        153  0.5882353
nani123456789/taxi-trip-fare-prediction                         Taxi Trip Fare Prediction                              3024126  2023-12-15 16:46:09.937000           2569         38  1
dhrubangtalukdar/airbnb-all-time-stock-data-latest              Airbnb All Time Stock Data (Latest)                      28424  2026-01-04 09:23:27.670000            330         34  1
bhavyarajdev/indian-railways-schedule-prices-availability-data  Indian Railways Schedule-Prices-Availability Data      7026565  2023-12-13 16:25:05.293000           1492         18  1
crailtap/street-network-of-new-york-in-graphml                  Street Network of New York in GraphML                  7580734  2017-08-03 10:12:03.063000           2077         31  0.875
dipam7/student-grade-prediction                                 Student Grade Prediction                                  7328  2018-09-14 15:34:04.550000          37664        391  0.7058824
danishammar/top-100-cities-weather-dataset                      Top 100 Cities Weather Dataset                            3186  2024-04-28 23:31:15.633000           1459         80  1
darkmatternet/global-earthquake-history-1m-since-1900           Global Earthquake History: 1M+ Since 1900             50535522  2026-08-12 20:32:59.663000            855         33  1
abdullahmeo/pakistan-tourism-trends-and-destinations-2015-24    Pakistan Tourism Trends & Destinations (2015-24).          950  2026-02-11 17:37:48.937000            153         30  1
dharun4772/doordash-eta-prediction                              DoorDash ETA Prediction                                5235865  2024-06-18 17:07:10.610000           1683         17  1
jinxzed/londonairbnb                                            LondonAirBNB                                         260095121  2020-09-15 08:22:48.663000            831         10  0.7647059
rohitgds/pan-india-bus-routes-35k-schedules-1000-cities         Pan-India Bus Routes: 35K+ Schedules, 1000+ Cities      486271  2025-09-01 14:02:36.447000            428         12  1

In [5]:
!kaggle datasets download -d ekaettesamuel/travel-time-prediction-in-lagos-nigeria

Dataset URL: https://www.kaggle.com/datasets/ekaettesamuel/travel-time-prediction-in-lagos-nigeria
License(s): MIT
Downloading travel-time-prediction-in-lagos-nigeria.zip to C:\Users\user\sam_work\traffic-congestion

  0%|          | 0.00/85.2k [00:00<?, ?B/s]
100%|##########| 85.2k/85.2k [00:00<00:00, 384kB/s]
100%|##########| 85.2k/85.2k [00:00<00:00, 382kB/s]

In [6]:
# Extracting 'zip' file 

import zipfile
import os

zip_file = "travel-time-prediction-in-lagos-nigeria.zip"

with zipfile.ZipFile(zip_file, "r") as zip_ref:
    zip_ref.extractall("traffic_data")

print("Dataset extracted successfully.")

Dataset extracted successfully.

In [7]:
# View the contents of the dataset

for root, dirs, files in os.walk("traffic_data"):
    for file in files:
        print(os.path.join(root, file))

In [8]:
# To read file

%pip install openpyxl

Requirement already satisfied: openpyxl in C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

In [9]:
# Convert file to dataFrame

import pandas as pd

df = pd.read_excel("C:/Users/user/sam_work/traffic_data/Travel_Time Prediction on Lagos_Ikorodu_Road Dataset .xlsx")
df.head()

,Vector,Description,Date,Year,Month,Day,Hour,Traffic Volume,Weather,Speed [km/h],Vehicle Type,Travel Time minutes
0,45,Ikorodu Road,2024-02-01 00:00:00,2024,2,1,0,10,haze,60.75,BRT,3
1,45,Ikorodu Road,2024-02-01 01:00:00,2024,2,1,1,127,haze,60.25,Yellow Bus,3
2,45,Ikorodu Road,2024-02-01 02:00:00,2024,2,1,2,89,haze,61.40,Mini Bus,3
3,45,Ikorodu Road,2024-02-01 03:00:00,2024,2,1,3,55,haze,60.53,Private,3
4,45,Ikorodu Road,2024-02-01 04:00:00,2024,2,1,4,53,haze,61.63,Yellow Bus,3

## EXPLORATORY DATA ANALYSIS

ANALYSIS

In [10]:
# Checking for data dimensions

df.shape

(1398, 12)

In [11]:
# Checking for data-type and non-null counts

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1398 entries, 0 to 1397
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Vector               1398 non-null   int64
 1   Description          1398 non-null   str
 2   Date                 1398 non-null   datetime64[us]
 3   Year                 1398 non-null   int64
 4   Month                1398 non-null   int64
 5   Day                  1398 non-null   int64
 6   Hour                 1398 non-null   int64
 7   Traffic Volume       1398 non-null   int64
 8   Weather              1385 non-null   str
 9   Speed [km/h]         1398 non-null   float64
 10  Vehicle Type         1398 non-null   str
 11  Travel Time minutes  1398 non-null   int64
dtypes: datetime64[us](1), float64(1), int64(7), str(3)
memory usage: 173.6 KB

In [12]:
# Check for basic statistics

df.describe()

,Vector,Date,Year,Month,Day,Hour,Traffic Volume,Speed [km/h],Travel Time minutes
count,1398.0,1398,1398.0,1398.000000,1398.000000,1398.000000,1398.000000,1398.000000,1398.000000
mean,45.0,2024-03-02 02:31:37.854077,2024.0,2.525036,15.400572,11.488555,495.761087,42.001030,7.542918
min,45.0,2024-02-01 00:00:00,2024.0,2.000000,1.000000,0.000000,10.000000,5.850000,2.000000
25%,45.0,2024-02-15 13:15:00,2024.0,2.000000,8.000000,5.250000,239.250000,22.240000,3.000000
50%,45.0,2024-03-02 10:30:00,2024.0,3.000000,15.000000,12.000000,560.500000,47.250000,4.000000
75%,45.0,2024-03-17 00:45:00,2024.0,3.000000,23.000000,17.000000,674.000000,59.810000,10.000000
max,45.0,2024-03-31 15:00:00,2024.0,3.000000,31.000000,23.000000,1651.000000,78.550000,38.000000
std,0.0,NaN,0.0,0.499552,8.732388,6.925171,281.130678,19.741012,6.590319

In [13]:
# Check for duplicate rows

print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [14]:
# Check for missing values

df.isnull().sum()

Vector                  0
Description             0
Date                    0
Year                    0
Month                   0
Day                     0
Hour                    0
Traffic Volume          0
Weather                13
Speed [km/h]            0
Vehicle Type            0
Travel Time minutes     0
dtype: int64

Handling Missing Values in the 'Weather' column

In [15]:
counts = df["Weather"].value_counts()

percentages = df["Weather"].value_counts(normalize=True, dropna=False) * 100

result = pd.DataFrame({
    "Count": counts,
    "Percentage": percentages.round(2)
})

result

                              Count  Percentage
Weather
broken clouds                 174.0       12.45
clear sky                      19.0        1.36
few clouds                    483.0       34.55
haze                          269.0       19.24
light intensity drizzle         1.0        0.07
light rain                     31.0        2.22
mist                            9.0        0.64
moderate rain                   1.0        0.07
overcast clouds               122.0        8.73
scattered clouds              230.0       16.45
thunderstorm                   23.0        1.65
thunderstorm with light rain   21.0        1.50
thunderstorm with rain          2.0        0.14
NaN                             NaN        0.93